### ISSUE TITLE
trying to install

### ISSUE THREAD

**Issue by arpecop** [shockone/black-screen#23] opened 2015-09-06 02:29 UTC
[05:26:58] Starting 'typescript'...
[05:26:59] Starting 'sass'...
[05:26:59] Starting 'react'...
[05:27:00] gulp-notify: [Black Screen Watcher] React has been compiled.
[05:27:01] Finished 'react' after 1.87 s
/Users/rudix/Desktop/black-screen/node_modules/typescript/lib/typescript.js:35171
            if (host.fileExists(fileName)) {
                     ^
TypeError: undefined is not a function

**Comment by freddyrangel** [comment] 2015-09-06 03:04
I'm getting the same error

**Comment by hdavidzhu** [comment] 2015-09-06 03:31
+1

**Comment by champo** [comment] 2015-09-06 03:43
This is a duplicate of #21

**Comment by shockone** [comment] 2015-09-06 10:22
Fixed.

**Closed by shockone** 2015-09-06 10:22 UTC
