### ISSUE TITLE
Enable ctrl+R history search

### ISSUE THREAD

**Issue by nbeydoon** [shockone/black-screen#421] opened 2016-05-30 15:52 UTC
This is one of the terminal feature I use the most, it would be great to have it !

And thanks for this beautiful terminal !

**Comment by shockone** [comment] 2016-05-30 15:53
Duplicate of https://github.com/shockone/black-screen/issues/260

**Closed by shockone** 2016-05-30 15:53 UTC

**Comment by nbeydoon** [comment] 2016-05-30 16:02
Oh, sorry don't see the issue
