### ISSUE TITLE
Only one letter displays at a time

### ISSUE THREAD

**Issue by aflyax** [shockone/black-screen#178] opened 2015-11-20 05:51 UTC
Typing next letter overrides the first one.

**Comment by shockone** [comment] 2015-11-20 11:35
@aflyax, can't reproduce, are you sure you have the latest master? Does anyone else experience this?

**Comment by iiegor** [comment] 2015-11-21 13:31
This problem is related with ``Aliases.ts``. Probably the ``Aliases.find()`` method is throwing an error like ``cannot read property 'undefined' of undefined``.

**Comment by Leonardo-Ciocan** [comment] 2016-01-09 22:25
I had the same thing happen on OSX 10.11 
stack trace:

````
bash: no job control in this shell
ATOM_SHELL_ASAR.js:153
        return old.apply(this, arguments);
                   ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:153:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:153:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/leo/Development/Github/black-screen/node_modules/ptyw.js/lib/pty.js:9:11)
    at Module._compile (module.js:425:26)
````

Some problem with one of the dependencies , I just ran `npm run recompile` and it works fine now

**Comment by shockone** [comment] 2016-01-16 09:41
Aliases are now loaded differently. Closing.

**Closed by shockone** 2016-01-16 09:41 UTC
