### ISSUE TITLE
Default window size

### ISSUE THREAD

**Issue by vicodinchik** [shockone/black-screen#414] opened 2016-05-29 18:44 UTC
When I run program at first time it appears fullscreen size, after I change it into size which is convenient to me and restart program - it still loads fullscreen. Would be a nice feature to keep user dimensions.

**Comment by shockone** [comment] 2016-05-29 18:45
Duplicate of https://github.com/shockone/black-screen/issues/224

**Closed by shockone** 2016-05-29 18:45 UTC

**Comment by shockone** [comment] 2016-05-30 13:30
@vicodinchik, fixed in  v0.0.11.
