### ISSUE TITLE
Black Screen does not load in for macOS Siera

### ISSUE THREAD

**Issue by TomSchillemans** [shockone/black-screen#769] opened 2016-09-21 17:26 UTC
I am am running macOS Siera right now and after installing Black Screen and trying to load it it doesn't load in fully.  

![screen shot 2016-09-21 at 19 23 19](https://cloud.githubusercontent.com/assets/3533733/18721522/31014ce2-8031-11e6-9dbb-5a2d9f0cd1d6.png)

Wondering why this is the case. Does it have something to do with Siera?

**Comment by drew-gross** [comment] 2016-09-21 18:47
Possibly. You can press `Command+Option+i` to open the developer console and look for error messages.

**Comment by TomSchillemans** [comment] 2016-09-21 18:50
I get this error: 
![screen shot 2016-09-21 at 20 49 42](https://cloud.githubusercontent.com/assets/3533733/18724518/f9aef972-803c-11e6-981b-ad6d324961d9.png)

**Comment by drew-gross** [comment] 2016-09-21 19:04
Interesting. That doesn't seem like it's related to Sierra. How did you install and how are you running black screen?

**Comment by TomSchillemans** [comment] 2016-09-21 19:08
I installed it via homebrew. And running it just via either spotlight or Application directly. So I guess it should have installed react if it needed it to.

**Comment by drew-gross** [comment] 2016-09-21 20:39
It should have. I'll install Sierra in a few days and see if I can reproduce this. It also might be fixed by the next push, if there was a problem with the build.

**Comment by noygal** [comment] 2016-09-21 22:38
I managed to reproduce it on 10.11.6:

```
brew cask uninstall black-screen
brew cask cleanup
brew cask install black-screen
```

I think it's related to the version mixup, issue: https://github.com/shockone/black-screen/issues/767

**Comment by zcdunn** [comment] 2016-09-22 16:43
I've got the same issue on Yosemite 10.10.5

**Comment by danevans** [comment] 2016-09-22 19:02
I also saw it on 10.11.6 El Capitan installing black screen 0.2.43 via brew. 

Opening a new tab causes the second error, if that helps.

![screen shot 2016-09-22 at 12 00 54 pm](https://cloud.githubusercontent.com/assets/214379/18762113/509d7aa4-80bc-11e6-902c-b204faffde1c.png)

**Comment by igas** [comment] 2016-09-23 02:05
I have the same, but without homebrew, I just downloaded it from releases and dragged to applications folder.

**Comment by devNaresh** [comment] 2016-09-23 03:40
even i am facing same issue...

**Comment by TomSchillemans** [comment] 2016-09-23 05:21
I might also add that I tried downloading a previous release from GitHub but that didn't work either!

**Comment by drew-gross** [comment] 2016-09-23 07:50
I fixed the deploy script, and it has deployed version 0.2.48, so this should be fixed now.

**Comment by TomSchillemans** [comment] 2016-09-23 08:00
Can anyone confirm? (I do not have access to a mac right now)

**Comment by drew-gross** [comment] 2016-09-23 08:25
@TomSchillemans you could try on Linux if that's what you have access to. It's not really supported but people have tried it and say it works fine for them.

**Comment by ruifilipeasilva** [comment] 2016-09-23 08:51
I'm still facing this problem :(

**Comment by igas** [comment] 2016-09-23 09:09
`Uncaught Error: Module version mismatch. Expected 50, got 48. ELECTRON_ASAR.js:168`

**Comment by noygal** [comment] 2016-09-23 12:56
Same here

**Comment by drew-gross** [comment] 2016-09-23 17:56
The module version mismatch is caused by a difference in the version of node you have and the version the native extensions are compiled for. I fixed this locally by running `npm rebuild`. If you've installed from source that should work, I'm not sure how you would fix this if you installed from brew. Maybe update your node version? I will keep investigating.

**Comment by shockone** [comment] 2016-09-23 18:40
@drew-gross, we need to build native extensions against Electron's V8 headers (Electron has a built-in node.js installation). It's handled by a package called `electron-rebuild`. Actually, you can see it being triggered as a part of modules installation here: https://github.com/shockone/black-screen/blob/master/package.json#L63 . I guess, using it instead of `npm rebuild` in this script will fix releases https://github.com/shockone/black-screen/blob/master/package.json#L65

**Comment by drew-gross** [comment] 2016-09-24 07:53
That does not seem to have worked: https://travis-ci.org/shockone/black-screen/builds/162390743 Maybe `npm rebuild` and `electron-rebuild` are both needed? I'll try that.

**Comment by drew-gross** [comment] 2016-09-24 08:06
Nope that didn't work either: https://travis-ci.org/shockone/black-screen/builds/162391783

I will continue investigating later.

**Comment by ehsangazar** [comment] 2016-09-24 13:12
I got this error, too
Uncaught Error: Module version mismatch. Expected 50, got 48.

**Comment by drew-gross** [comment] 2016-09-24 19:02
Updating the node version also didn't work: https://travis-ci.org/shockone/black-screen/builds/162466928

**Comment by pedrocorreia** [comment] 2016-09-26 10:18
I was getting the same issue, (missing react module) with El Capitan, however after upgrading to Sierra and uninstalling and reinstalling the latest version of black screen i get a different error on the console.

![screen shot 2016-09-26 at 11 08 46](https://cloud.githubusercontent.com/assets/219789/18830812/50c69ca6-83da-11e6-8c14-51f6e5a492e6.png)

Please note the divergence in version numbers in the terminal screenshot.

```Downloading https://github.com/shockone/black-screen/releases/download/v0.2.53/black-screen-0.2.48-mac.zip````

And the new error on OS X Sierra

<img width="1280" alt="screen shot 2016-09-26 at 11 08 46 2" src="https://cloud.githubusercontent.com/assets/219789/18830921/dd7af37c-83da-11e6-94b3-352af1af06c2.png">

**Comment by pedrocorreia** [comment] 2016-09-26 10:27
Sorry for the added comment but running black-screen from my local repo, works fine while "building" a zipped bundle fails.

``` terminal
 2016-09-26 11:22:24 ☆  blobsnark in ~/dev/black-screen
± |master ✓| → npm run pack

> black-screen@0.2.53 pack /Users/pedrocorreia/dev/black-screen
> npm run compile && build


> black-screen@0.2.53 compile /Users/pedrocorreia/dev/black-screen
> npm run cleanup && npm run tsc && npm run copy-html


> black-screen@0.2.53 cleanup /Users/pedrocorreia/dev/black-screen
> rm -rf compiled/src


> black-screen@0.2.53 tsc /Users/pedrocorreia/dev/black-screen
> tsc


> black-screen@0.2.53 copy-html /Users/pedrocorreia/dev/black-screen
> mkdir -p compiled/src/views && cp src/views/index.html compiled/src/views

Warning: Specified application directory "." equals to project dir — superfluous or wrong configuration
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform darwin x64 using electron 1.4.1 to dist/mac

Warning: app-category-type is deprecated, please set as build.mac.category
Warning: App is not signed: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Must be "Developer ID Application:" or custom non-Apple code signing certificate
Creating DMG
Creating MacOS zip
Error: Module version mismatch. Expected 48, got 50.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pedrocorreia/dev/black-screen/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pedrocorreia/dev/black-screen/node_modules/macos-alias/index.js:1:18)
From previous event:
    at tsAwaiter (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at DmgTarget.build (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/targets/dmg.ts:33:32)
    at MacPackager.packageInDistributableFormat (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/macPackager.ts:195:30)
    at nonMasPromise.doPack.then.then (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/macPackager.ts:80:44)
From previous event:
    at MacPackager.<anonymous> (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/macPackager.ts:79:14)
    at next (native)
From previous event:
    at tsAwaiter (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/builder.ts:181:52)
    at Object.<anonymous> (/Users/pedrocorreia/dev/black-screen/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/Users/pedrocorreia/dev/black-screen/node_modules/.bin/npm" "run" "pack"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.2.53 pack: `npm run compile && build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the black-screen@0.2.53 pack script 'npm run compile && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pedrocorreia/dev/black-screen/npm-debug.log
```

Essentially the error seems to be the same version mismatch:

```Error: Module version mismatch. Expected 48, got 50.```

**Comment by jwhitmarsh** [comment] 2016-09-26 12:25
Brew installation on macOS 10.11.6 returns the same `Error: Module version mismatch. Expected 48, got 50`

**Comment by pmatias** [comment] 2016-09-26 12:48
Same error here with macOS 10.12 `Error: Module version mismatch. Expected 48, got 50`

**Comment by seenukarthi** [comment] 2016-09-26 15:13
I'm also getting the `Error: Module version mismatch. Expected 48, got 50` in macOS 10.12

**Comment by B-lvlax** [comment] 2016-09-26 17:34
The same thing on Capitan 10.11.6 from the version 0.2.38 of Black Screen. Version 0.2.37 continue to work form me.

**Comment by ylluminate** [comment] 2016-09-27 20:39
Same white screen of death here as well on 10.11.6 from Homebrew cask.

**Comment by drew-gross** [comment] 2016-09-28 05:51
I believe I have finally fixed this issue. Closing for now, if people continue to see problems on 0.2.55 I will reopen.

**Closed by drew-gross** 2016-09-28 05:51 UTC

**Comment by pmatias** [comment] 2016-09-28 12:00
I can confirm that new release worked for me.

Thanks for the quick fix!

**Comment by pedrocorreia** [comment] 2016-09-28 14:31
I confirm that v0.2.55 works.

**Comment by lejahmie** [comment] 2017-01-23 09:55
I also get "white screen" running macOs Sierra 10.12.1 (16B2657) on my MacBook Pro (15 tum, early 2011), 2,2 GHz Intel Core i7, 8 GB 1333 MHz DDR3, AMD Radeon HD 6750M 1024 MB, Intel HD Graphics 3000 512 MB.

**Get following error in console:** 
`Uncaught (in promise) Can't parse alias line: {`

Black-Screen 0.2.93 installed via brew.

**Comment by hotcoder** [comment] 2017-09-21 13:13
White Screen is coming after installing Upterm version v0.4.1/upterm-0.4.1-x86_64-macOS.dmg on macOS Sierra 10.12.6
